### ISSUE TITLE
Evolutions 起動エラー発生

### ISSUE THREAD

**Issue by Zorba-Croooober** [cryuya/bb-playframework#1]
https://github.com/cryuya/bb-playframework/blob/c9accbc2943d89bc41df5ebb2f7e1a982a9e0ee9/conf/evolutions/default/1.sql#L25

ここは「-- !Downs 」じゃないですか？

**Comment by zero-to-yoshino** [comment]
これ僕も思いました

**Comment by cryuya** [comment]
githubに上げるときに手違いでコメントが消えてました。
