### ISSUE TITLE
 com.google.common.collect.Lists.newArrayList()

### ISSUE THREAD

**Issue by zero-to-yoshino** [cryuya/bb-playframework#4]
先にインポートしておくと可読性が高まるかなと思います。
`import com.google.common.collect.Lists;`

**Comment by cryuya** [comment]
@zero-to-yoshino 
見返してみましたが、そちらのほうが良さそう ~~なので書き換えておきます。~~ です。

**Comment by zero-to-yoshino** [comment]
@cryuya 
多分今日はこういった感じでIssueにあげたもので、佐々木さんが実施しても良いと思った修正を僕がするという流れだと思うので、これは僕が修正したいと思うのですがいいでしょうか。（逆にそれ以外のものはいじりません。）

**Comment by cryuya** [comment]
@zero-to-yoshino 
コメント編集しました。そうですね。よろしくおねがいします。
